"use client"

import { Sparkles } from "lucide-react"
import { useLanguage } from "@/components/LanguageProvider"
import type { AIReport } from "@/types/report"

// AiReportPanel 展示 AI 生成的“可读报告”。
// 重点：AI 不应该直接拿隐私原始数据写报告；
// 它应该只基于 proof 的公开输出生成摘要。
export function AiReportPanel({ report }: { report: AIReport }) {
  const { language, t } = useLanguage()

  return (
    <section className="border border-[var(--line)] bg-white p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Sparkles className="text-[var(--gold)]" size={20} />
          <p className="text-xs font-semibold uppercase text-[var(--moss)]">
            {language === "zh" ? "可分享的 AI 报告" : "Shareable AI Report"}
          </p>
        </div>
        <span className="bg-[#e6efe2] px-3 py-2 text-xs font-semibold text-[var(--forest)]">
          {language === "zh" ? "已验证" : "Verified"}
        </span>
      </div>
      <h2 className="mt-4 text-2xl font-semibold">{report.title}</h2>
      <p className="mt-4 text-base leading-7 text-[var(--ink)]">
        {report.summary}
      </p>
      <ul className="mt-5 grid gap-3">
        {report.bullets.map((bullet) => (
          <li className="border-l-2 border-[var(--gold)] bg-[#fbfcf8] p-3 pl-4 text-sm leading-6" key={bullet}>
            {bullet}
          </li>
        ))}
      </ul>
      <details className="mt-5 border-t border-[var(--line)] pt-4">
        <summary className="cursor-pointer text-xs font-semibold uppercase text-[var(--moss)]">
          {language === "zh" ? "技术来源" : "Technical Source"}
        </summary>
        <p className="mt-2 text-xs leading-5 text-[var(--muted)]">
          {report.source === "deepseek-v4"
            ? language === "zh"
              ? `由 DeepSeek V4 生成，模型：${report.model ?? "deepseek-v4-pro"}。输入仅包含公开证明结果。`
              : `Generated by DeepSeek V4, model: ${report.model ?? "deepseek-v4-pro"}. Input contains disclosed proof outputs only.`
            : t("aiReportLabel")}
        </p>
      </details>
    </section>
  )
}
